# Generated by Django 4.0 on 2021-12-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyId', models.CharField(max_length=10)),
                ('dateOfPurchase', models.CharField(max_length=10)),
                ('fuel', models.CharField(max_length=6)),
                ('vehicleSegment', models.CharField(max_length=1)),
                ('premium', models.IntegerField(max_length=7)),
                ('bodyInjuryLiability', models.IntegerField(max_length=1)),
                ('personalInjuryProtection', models.IntegerField(max_length=1)),
                ('propertyDamageLiability', models.IntegerField(max_length=1)),
                ('collision', models.IntegerField(max_length=1)),
                ('comprehension', models.IntegerField(max_length=1)),
            ],
        ),
    ]
