# Generated by Django 4.0 on 2021-12-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='id',
        ),
        migrations.AlterField(
            model_name='records',
            name='policyId',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
