# Generated by Django 4.0 on 2021-12-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_remove_records_id_alter_records_policyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='bodyInjuryLiability',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='records',
            name='collision',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='records',
            name='comprehension',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='records',
            name='personalInjuryProtection',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='records',
            name='premium',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='records',
            name='propertyDamageLiability',
            field=models.IntegerField(),
        ),
    ]
