# Generated by Django 4.0 on 2021-12-12 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policy', '0003_alter_records_bodyinjuryliability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('customerId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=5)),
                ('incomeGroup', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=50)),
                ('martialStatus', models.IntegerField()),
                ('policyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.records')),
            ],
        ),
    ]
