# Generated by Django 4.0 on 2021-12-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='policyId',
            field=models.CharField(max_length=10),
        ),
    ]
