# Generated by Django 4.0 on 2021-12-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_records_policyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='customerId',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='records',
            name='policyId',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
