# Generated by Django 4.0 on 2021-12-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_records_customerid_alter_records_policyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='gender',
            field=models.CharField(max_length=6),
        ),
    ]
